plugins:
  - jekyll-seo-tag

collections:
  papers:
    output: false
    permalink: /:collection/:slug:output_ext

images_location: /assets/img

# --- SEO ---

tagline: Personal website of Pushkal Mishra
description: "Pushkal Mishra is a researcher interested in Radar Imaging and Autonomous Driving. He is a PhD student at University of California San Diego."
logo: &logo /assets/img/logo.png

# Logo is weird, needs to be set as a site-wide default
defaults:
  - scope:
      path: ""
    values:
      image: *logo

author:
  twitter: &twitter PushkalM11

twitter:
  username: *twitter
  card: summary

webmaster_verifications:
  google: zrD-uBE3PiX6K7_miYRvKT3SC7pPJuxvXIhgH7kZLMY

locale: en_US

# --- SEO ends ---

google_analytics: G-033ZGR8MHH